
CREATE OR REPLACE TABLE DW.DIM_DATE (
  SK_DATE        NUMBER AUTOINCREMENT START 1 INCREMENT 1,   -- PK surrogate
  DATE_VALUE     DATE        NOT NULL,                       -- UK (actual date)

  YEAR           NUMBER      NOT NULL,
  QUARTER        NUMBER      NOT NULL,
  MONTH          NUMBER      NOT NULL,
  WEEK_OF_YEAR   NUMBER      NOT NULL,
  IS_WEEKEND     STRING(1)   NOT NULL,                       -- 'Y'/'N'

  LOAD_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  CONSTRAINT PK_DIM_DATE PRIMARY KEY (SK_DATE),
  CONSTRAINT UK_DIM_DATE UNIQUE (DATE_VALUE)
);


CREATE OR REPLACE TABLE RETAIL_DB.DW.DIM_STORE (
    SK_STORE    NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    STORE_ID    VARCHAR(50) NOT NULL,
    STORE_NAME  VARCHAR(200),
    REGION      VARCHAR(50),
    CITY        VARCHAR(100),
    STATE       VARCHAR(50),
    COUNTRY     VARCHAR(50),
    OPEN_DATE   DATE,
    STATUS      VARCHAR(20),
    CONSTRAINT PK_DIM_STORE PRIMARY KEY (SK_STORE)
);





CREATE OR REPLACE TABLE RETAIL_DB.DW.DIM_CUSTOMER (
    SK_CUSTOMER NUMBER IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    NAME        VARCHAR(150),
    EMAIL       VARCHAR(150),
    PHONE       VARCHAR(50),
    SEGMENT     VARCHAR(50),
    CITY        VARCHAR(100),
    STATE       VARCHAR(50),

    EFF_START_TS TIMESTAMP,
    EFF_END_TS   TIMESTAMP,
    IS_CURRENT   VARCHAR(1)


);

CREATE OR REPLACE TABLE RETAIL_DB.DW.DIM_PRODUCT (

    SK_PRODUCT NUMBER IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID        VARCHAR(50) NOT NULL,
    PRODUCT_NAME      VARCHAR(200),
    CATEGORY          VARCHAR(100),
    SUBCATEGORY       VARCHAR(100),
    BRAND             VARCHAR(100),
    UNIT_PRICE        NUMBER(10,2),
    STATUS            VARCHAR(20),
    EFF_START_TS      TIMESTAMP_NTZ,
    EFF_END_TS        TIMESTAMP_NTZ,
    IS_CURRENT        VARCHAR(1)
);



CREATE OR REPLACE TABLE RETAIL_DB.DW.FACT_SALES(

    ORDER_ID          VARCHAR(50) NOT NULL,
    ORDER_LINE_ID     NUMBER(10,0) NOT NULL,

    SK_DATE           NUMBER(38,0) NOT NULL,
    SK_STORE          NUMBER(38,0) NOT NULL,
    SK_CUSTOMER       NUMBER(38,0) NOT NULL,
    SK_PRODUCT        NUMBER(38,0) NOT NULL,

    QTY               NUMBER(10,0),
    UNIT_PRICE        NUMBER(10,2),
    DISCOUNT_PCT      NUMBER(5,2),
    GROSS_AMOUNT      NUMBER(18,2),
    DISCOUNT_AMOUNT   NUMBER(18,2),
    NET_AMOUNT        NUMBER(18,2),

    PAYMENT_TYPE      VARCHAR(30),
    ORDER_STATUS      VARCHAR(30),

    LOAD_TS           TIMESTAMP_NTZ,

    CONSTRAINT PK_SALES_SRC 
    PRIMARY KEY (ORDER_ID, ORDER_LINE_ID)

);


MERGE INTO RETAIL_DB_CLONE.DW.FACT_SALES f
USING (
  WITH src_clean AS (
    SELECT
      s.ORDER_ID,
      s.ORDER_LINE_ID,
      s.ORDER_DATE,
      s.STORE_ID,
      s.CUSTOMER_ID,
      s.PRODUCT_ID,

      /* Safe numeric parsing */
      TRY_TO_NUMBER(s.QTY)        AS QTY_N,
      TRY_TO_NUMBER(s.UNIT_PRICE) AS UNIT_PRICE_N,
      TRY_TO_NUMBER(s.DISCOUNT_PCT) AS DISCOUNT_PCT_N,

      s.PAYMENT_TYPE,
      s.ORDER_STATUS
    FROM RETAIL_DB_CLONE.DW."fact_sales_18k" s
  ),
  src_valid AS (
    SELECT
      ORDER_ID,
      ORDER_LINE_ID,
      ORDER_DATE,
      STORE_ID,
      CUSTOMER_ID,
      PRODUCT_ID,

      /* Apply rules: qty/unit_price required, discount default + range */
      QTY_N,
      UNIT_PRICE_N,
      IFF(DISCOUNT_PCT_N IS NULL, 0,
          IFF(DISCOUNT_PCT_N < 0, 0,
              IFF(DISCOUNT_PCT_N > 100, 100, DISCOUNT_PCT_N)
          )
      ) AS DISCOUNT_PCT_FIXED,

      PAYMENT_TYPE,
      ORDER_STATUS
    FROM src_clean
    WHERE ORDER_ID IS NOT NULL
      AND ORDER_LINE_ID IS NOT NULL
      AND ORDER_DATE IS NOT NULL
      AND STORE_ID IS NOT NULL
      AND CUSTOMER_ID IS NOT NULL
      AND PRODUCT_ID IS NOT NULL
      AND QTY_N IS NOT NULL
      AND UNIT_PRICE_N IS NOT NULL
      AND QTY_N >= 0
      AND UNIT_PRICE_N >= 0
  ),
  /* Deduplicate source keys (pick one row per ORDER_ID + ORDER_LINE_ID) */
  src_dedup AS (
    SELECT *
    FROM src_valid
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY ORDER_ID, ORDER_LINE_ID
      ORDER BY ORDER_DATE DESC
    ) = 1
  )
  SELECT
    s.ORDER_ID,
    s.ORDER_LINE_ID,

    d.SK_DATE,
    st.SK_STORE,
    c.SK_CUSTOMER,
    p.SK_PRODUCT,

    s.QTY_N::NUMBER(10,0) AS QTY,
    s.UNIT_PRICE_N::NUMBER(10,2) AS UNIT_PRICE,
    s.DISCOUNT_PCT_FIXED::NUMBER(5,2) AS DISCOUNT_PCT,

    ROUND(s.QTY_N * s.UNIT_PRICE_N, 2) AS GROSS_AMOUNT,
    ROUND((s.QTY_N * s.UNIT_PRICE_N) * (s.DISCOUNT_PCT_FIXED/100), 2) AS DISCOUNT_AMOUNT,
    ROUND((s.QTY_N * s.UNIT_PRICE_N) - ((s.QTY_N * s.UNIT_PRICE_N) * (s.DISCOUNT_PCT_FIXED/100)), 2) AS NET_AMOUNT,

    s.PAYMENT_TYPE,
    s.ORDER_STATUS,

    CURRENT_TIMESTAMP() AS LOAD_TS
  FROM src_dedup s
  JOIN RETAIL_DB_CLONE.DW.DIM_DATE d
    ON d.DATE_VALUE = s.ORDER_DATE
  JOIN RETAIL_DB_CLONE.DW.DIM_STORE st
    ON st.STORE_ID = s.STORE_ID
  JOIN RETAIL_DB_CLONE.DW.DIM_CUSTOMER c
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
   AND c.IS_CURRENT = 'Y'
  JOIN RETAIL_DB_CLONE.DW.DIM_PRODUCT p
    ON p.PRODUCT_ID = s.PRODUCT_ID
   AND p.IS_CURRENT = 'Y'
) src
ON f.ORDER_ID = src.ORDER_ID
AND f.ORDER_LINE_ID = src.ORDER_LINE_ID

WHEN MATCHED THEN UPDATE SET
  f.SK_DATE         = src.SK_DATE,
  f.SK_STORE        = src.SK_STORE,
  f.SK_CUSTOMER     = src.SK_CUSTOMER,
  f.SK_PRODUCT      = src.SK_PRODUCT,
  f.QTY             = src.QTY,
  f.UNIT_PRICE      = src.UNIT_PRICE,
  f.DISCOUNT_PCT    = src.DISCOUNT_PCT,
  f.GROSS_AMOUNT    = src.GROSS_AMOUNT,
  f.DISCOUNT_AMOUNT = src.DISCOUNT_AMOUNT,
  f.NET_AMOUNT      = src.NET_AMOUNT,
  f.PAYMENT_TYPE    = src.PAYMENT_TYPE,
  f.ORDER_STATUS    = src.ORDER_STATUS,
  f.LOAD_TS         = src.LOAD_TS

WHEN NOT MATCHED THEN INSERT (
  ORDER_ID, ORDER_LINE_ID,
  SK_DATE, SK_STORE, SK_CUSTOMER, SK_PRODUCT,
  QTY, UNIT_PRICE, DISCOUNT_PCT,
  GROSS_AMOUNT, DISCOUNT_AMOUNT, NET_AMOUNT,
  PAYMENT_TYPE, ORDER_STATUS,
  LOAD_TS
) VALUES (
  src.ORDER_ID, src.ORDER_LINE_ID,
  src.SK_DATE, src.SK_STORE, src.SK_CUSTOMER, src.SK_PRODUCT,
  src.QTY, src.UNIT_PRICE, src.DISCOUNT_PCT,
  src.GROSS_AMOUNT, src.DISCOUNT_AMOUNT, src.NET_AMOUNT,
  src.PAYMENT_TYPE, src.ORDER_STATUS,
  src.LOAD_TS
);


SHOW TABLES;

SELECT * FROM FACT_SALES;






CREATE OR REPLACE VIEW RETAIL_DB_CLONE.SEMANTIC.VW_SALES_SEMANTIC AS
SELECT
  f.ORDER_ID,
  f.ORDER_LINE_ID,

  d.DATE_VALUE,
  d.YEAR,
  d.QUARTER,
  d.MONTH,
  d.WEEK_OF_YEAR,
  d.IS_WEEKEND,

  st.STORE_ID,
  st.STORE_NAME,
  st.REGION,
  st.CITY    AS STORE_CITY,
  st.STATE   AS STORE_STATE,
  st.COUNTRY,
  st.STATUS  AS STORE_STATUS,

  c.CUSTOMER_ID,
  c.NAME     AS CUSTOMER_NAME,
  c.SEGMENT  AS CUSTOMER_SEGMENT,
  c.CITY     AS CUSTOMER_CITY,
  c.STATE    AS CUSTOMER_STATE,

  p.PRODUCT_ID,
  p.PRODUCT_NAME,
  p.CATEGORY,
  p.SUBCATEGORY,
  p.BRAND,
  p.STATUS   AS PRODUCT_STATUS,

  f.QTY,
  f.UNIT_PRICE,
  f.DISCOUNT_PCT,
  f.GROSS_AMOUNT,
  f.DISCOUNT_AMOUNT,
  f.NET_AMOUNT,

  f.PAYMENT_TYPE,
  f.ORDER_STATUS,
  f.LOAD_TS
FROM RETAIL_DB_CLONE.DW.FACT_SALES f
JOIN RETAIL_DB_CLONE.DW.DIM_DATE d
  ON f.SK_DATE = d.SK_DATE
JOIN RETAIL_DB_CLONE.DW.DIM_STORE st
  ON f.SK_STORE = st.SK_STORE
JOIN RETAIL_DB_CLONE.DW.DIM_CUSTOMER c
  ON f.SK_CUSTOMER = c.SK_CUSTOMER AND c.IS_CURRENT = 'Y'
JOIN RETAIL_DB_CLONE.DW.DIM_PRODUCT p
  ON f.SK_PRODUCT = p.SK_PRODUCT AND p.IS_CURRENT = 'Y';



CREATE OR REPLACE VIEW RETAIL_DB_CLONE.SEMANTIC.VW_SALES_KPI AS
SELECT
  DATE_VALUE,
  YEAR,
  MONTH,
  ORDER_ID,
  NET_AMOUNT,
  QTY
FROM RETAIL_DB_CLONE.SEMANTIC.VW_SALES_SEMANTIC;



create or replace schema dynamic;

CREATE OR REPLACE DYNAMIC TABLE RETAIL_DB.dynamic.DT_SALES_WIDE
TARGET_LAG = '30 minutes'
WAREHOUSE = COMPUTE_WH
AS
SELECT
  f.ORDER_ID,
  f.ORDER_LINE_ID,

  d.DATE_VALUE,
  d.YEAR,
  d.QUARTER,
  d.MONTH,
  d.WEEK_OF_YEAR,
  d.IS_WEEKEND,

  st.STORE_ID,
  st.STORE_NAME,
  st.REGION,
  st.CITY    AS STORE_CITY,
  st.STATE   AS STORE_STATE,
  st.COUNTRY,
  st.STATUS  AS STORE_STATUS,

  c.CUSTOMER_ID,
  c.NAME     AS CUSTOMER_NAME,
  c.SEGMENT  AS CUSTOMER_SEGMENT,
  c.CITY     AS CUSTOMER_CITY,
  c.STATE    AS CUSTOMER_STATE,

  p.PRODUCT_ID,
  p.PRODUCT_NAME,
  p.CATEGORY,
  p.SUBCATEGORY,
  p.BRAND,
  p.STATUS   AS PRODUCT_STATUS,

  f.QTY,
  f.UNIT_PRICE,
  f.DISCOUNT_PCT,
  f.GROSS_AMOUNT,
  f.DISCOUNT_AMOUNT,
  f.NET_AMOUNT,

  f.PAYMENT_TYPE,
  f.ORDER_STATUS,
  f.LOAD_TS
FROM RETAIL_DB_CLONE.DW.FACT_SALES f
JOIN RETAIL_DB_CLONE.DW.DIM_DATE d
  ON f.SK_DATE = d.SK_DATE
JOIN RETAIL_DB_CLONE.DW.DIM_STORE st
  ON f.SK_STORE = st.SK_STORE
JOIN RETAIL_DB_CLONE.DW.DIM_CUSTOMER c
  ON f.SK_CUSTOMER = c.SK_CUSTOMER AND c.IS_CURRENT = 'Y'
JOIN RETAIL_DB_CLONE.DW.DIM_PRODUCT p
  ON f.SK_PRODUCT = p.SK_PRODUCT AND p.IS_CURRENT = 'Y';



CREATE OR REPLACE SCHEMA SEMANTIC_DOCS;

CREATE OR REPLACE TABLE SEMANTIC_DOCS.DOCS (
  DOC_ID       NUMBER AUTOINCREMENT,
  DOC_NAME     STRING,
  DOC_TYPE     STRING,         -- HLD / SOP / KPI / GLOSSARY
  PAGE         NUMBER,
  CHUNK        STRING,         -- searchable text
  SOURCE       STRING,         -- file name or url/path
  UPDATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO SEMANTIC_DOCS.DOCS (DOC_NAME, DOC_TYPE, PAGE, CHUNK, SOURCE)
VALUES
('Retail Sales Analytics HLD', 'HLD', 1,
 'Executive Summary: End-to-end Retail Sales Analytics on Snowflake using Snowpipe, Informatica CDI, Star Schema, Streamlit, Cortex Search (RAG), and Cortex Analyst (NLQ).',
 'HLD_2026-01-26'),

('Retail Sales Analytics HLD', 'HLD', 2,
 'Objectives: near real-time ingestion (<5 min), star schema analytics, SCD2 for Customer/Product, Streamlit dashboards, RAG with citations, governed NLQ using semantic views.',
 'HLD_2026-01-26'),

('Retail Sales Analytics HLD', 'HLD', 3,
 'Flow: files land → Snowpipe to RAW → CDI loads DIM_DATE → DIM_STORE → DIM_CUSTOMER(SCD2) → DIM_PRODUCT(SCD2) → FACT_SALES → Streamlit consumption; RAG uses Cortex Search; NLQ uses Cortex Analyst.',
 'HLD_2026-01-26');

 CREATE OR REPLACE CORTEX SEARCH SERVICE SEMANTIC_DOCS.DOC_SEARCH_SVC
  ON CHUNK
  ATTRIBUTES DOC_NAME, DOC_TYPE, PAGE, SOURCE
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '30 minutes'
AS
SELECT
  CHUNK,
  DOC_NAME,
  DOC_TYPE,
  PAGE,
  SOURCE
FROM RETAIL_DB_CLONE.SEMANTIC_DOCS.DOCS;




SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE();
SHOW CORTEX SEARCH SERVICES IN SCHEMA RETAIL_DB_CLONE.SEMANTIC_DOCS;

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';


show tables;


SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();

SHOW CORTEX SEARCH SERVICES;
SHOW CORTEX SEARCH SERVICES IN DATABASE RETAIL_DB_CLONE;
SHOW CORTEX SEARCH SERVICES IN SCHEMA RETAIL_DB_CLONE.SEMANTIC_DOCS;
