CREATE OR REPLACE TABLE RETAIL_DB.DW.DIM_CUSTOMER (

    
    SK_CUSTOMER NUMBER IDENTITY(1,1) PRIMARY KEY,

    CUSTOMER_ID VARCHAR(50) NOT NULL,

    NAME        VARCHAR(150),
    EMAIL       VARCHAR(150),
    PHONE       VARCHAR(50),
    SEGMENT     VARCHAR(50),
    CITY        VARCHAR(100),
    STATE       VARCHAR(50),

    EFF_START_TS TIMESTAMP,
    EFF_END_TS   TIMESTAMP,
    IS_CURRENT   VARCHAR(1)


);


show tables;


select * from sales_srcc;

SHOW TABLES;

SELECT * FROM CUST_DIM2;


SELECT * FROM DIM_PRO;



SELECT * FROM dim_customer;

TRUNCATE TABLE DIM_CUSTOMER;


SELECT * FROM RAW_SALES;


CREATE OR REPLACE TABLE RETAIL_DB.QUARANTINE.SALES_SRC (

    ORDER_ID          VARCHAR(50) NOT NULL,
    ORDER_LINE_ID     NUMBER(10,0) NOT NULL,

    SK_DATE           NUMBER(38,0) NOT NULL,
    SK_STORE          NUMBER(38,0) NOT NULL,
    SK_CUSTOMER       NUMBER(38,0) NOT NULL,
    SK_PRODUCT        NUMBER(38,0) NOT NULL,

    QTY               NUMBER(10,0),
    UNIT_PRICE        NUMBER(10,2),
    DISCOUNT_PCT      NUMBER(5,2),
    GROSS_AMOUNT      NUMBER(18,2),
    DISCOUNT_AMOUNT   NUMBER(18,2),
    NET_AMOUNT        NUMBER(18,2),

    PAYMENT_TYPE      VARCHAR(30),
    ORDER_STATUS      VARCHAR(30),

    LOAD_TS           TIMESTAMP_NTZ,

    CONSTRAINT PK_SALES_SRC 
    PRIMARY KEY (ORDER_ID, ORDER_LINE_ID)

);


SELECT * FROM SALES_SRCC;




show tables;


select * from source_sales_fact;

